name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [7.3, 7.4, 8.0]
        composer_flags: ['', '--prefer-lowest']

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v5
      with:
        php_version: ${{ matrix.php_version }}
        args: ${{ matrix.composer_flags }}
        command: update
    - uses: php-actions/phpunit@v3
      with:
        version: 8
        php_version: ${{ matrix.php_version }}
        args: '--coverage-clover ./tests/logs/clover.xml'
        php_extensions: xdebug
      env:
          XDEBUG_MODE: coverage
    - uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: ./tests/logs/clover.xml

  coveralls:
    needs: build-test
    runs-on: ubuntu-latest
    if: always()
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: code-coverage-report
    - uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: clover.xml

